### PR TITLE
Reuse HTTP sessions

### PR DESCRIPTION
**Pull request by sam-myers**

### CODE REVIEW

**Comment by LaughlinElkind** [comment]
LGTM for little wins

**Comment by htmldoug** [comment]
Golden rule of perf optimization is to measure.
What were the numbers before and after?

**Comment by LaughlinElkind** [comment]
Before: Running load test takes cluster down
After: Probably the same thing

**Comment by mattminer-rally** [comment]
Not sure this is the repo you want to adjust anyway. marathon-lb-rally is the one we use. Would need to coordinate with @tylermarshall because of some request blocking logic that still lives there.

**Comment by mfbaker** [comment]
```
FROM docker.werally.in/marathon-lb:1.6.0.2
```

**Pull request closed without merging**
